-- MySQL Script generated by MySQL Workbench
-- Mon Feb 24 23:47:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema calendario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `calendario` ;

-- -----------------------------------------------------
-- Schema calendario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `calendario` DEFAULT CHARACTER SET utf8 ;
USE `calendario` ;

-- -----------------------------------------------------
-- Table `calendario`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `calendario`.`user` ;

CREATE TABLE IF NOT EXISTS `calendario`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `calendario`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `calendario`.`event` ;

CREATE TABLE IF NOT EXISTS `calendario`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `start` TIMESTAMP NOT NULL,
  `end` TIMESTAMP NOT NULL,
  `startTime` TIMESTAMP NOT NULL,
  `creatorID` INT NOT NULL,
  `endTime` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_event_user_idx` (`creatorID` ASC) VISIBLE,
  CONSTRAINT `fk_event_user`
    FOREIGN KEY (`creatorID`)
    REFERENCES `calendario`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `calendario`.`invitation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `calendario`.`invitation` ;

CREATE TABLE IF NOT EXISTS `calendario`.`invitation` (
  `user_from` INT NOT NULL,
  `user_to` INT NOT NULL,
  `event_id` INT NOT NULL,
  `answer` INT NULL,
  PRIMARY KEY (`user_from`, `user_to`),
  INDEX `fk_user_has_user_user2_idx` (`user_to` ASC) VISIBLE,
  INDEX `fk_user_has_user_user1_idx` (`user_from` ASC) VISIBLE,
  INDEX `fk_invitation_event1_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`user_from`)
    REFERENCES `calendario`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_user2`
    FOREIGN KEY (`user_to`)
    REFERENCES `calendario`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invitation_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `calendario`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
